/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_kervala_comicsreader_RarFile */

#ifndef _Included_net_kervala_comicsreader_RarFile
#define _Included_net_kervala_comicsreader_RarFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_kervala_comicsreader_RarFile
 * Method:    nativeGetEntries
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_kervala_comicsreader_RarFile_nativeGetEntries
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_kervala_comicsreader_RarFile
 * Method:    nativeGetData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_kervala_comicsreader_RarFile_nativeGetData
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     net_kervala_comicsreader_RarFile
 * Method:    nativeGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_kervala_comicsreader_RarFile_nativeGetVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
